### ISSUE TITLE
Azure Support

### ISSUE THREAD

**Issue by GABeech** [opserver/Opserver#240]
This issue will serve as the central point for managing
the progress of Azure support.

The initial support will be focused on collecting Metrics and basic
data about Azure resources.

If anyone has any requests, opinions or ideas on what should be supported please chime in here.

## Branch Isolation

We want plugin support to be in before supporting Azure
as part of the main poject. While this work is on going Azure work will
be isolated to the Azure branch.

If you want to run any of the features being developed for Azure you will
need to run that branch.

## Tasks for initial support

This is a small subset of Azure information that will be used to for the
initial coding.

### Pre-requsites

Setup generic Azure Metric Data Collection:

- [ ] Azure Authentication
- [ ] Initial Data Models for Azure Metrics
- [ ] Able to Query Azure Metrics API (formally Insights API)

### Resources

For each resource we support we need to ask three basic questions:

1. Figure out what makes sense to replicate from current Setup
1. What code can we keep (Works both On Prem & In Azure)
1. Figure out what Azure only things we want to add

#### Supported resources

- [ ] Azure SQL
- [ ] Azure Redis
- [ ] Azure Windows VM

**General Questions for all resources:**

1. What is Unique to Azure that we need to implement
1. Is is better to get the resources information from the metrics API than SQL Queries
    * Can we get the same info but at low 'cost' (e.g. No DTU usage when hitting API)?

#### Azure SQL Support

**Instance View:**

- [ ] Summary
- [ ] Stats
- [ ] Performance
- [ ] Waits
- [ ] Cache
- [ ] Memory and Storage

**Database View:**

- [ ] Tables
- [ ] Views
- [ ] Backups
- [ ] Restores

#### Azure Redis Support

**Instance View:**

- [ ] Summary
- [ ] Stats
- [ ] Memory
- [ ] Replication
- [ ] Clients
- [ ] Keyspace
- [ ] Slow Log

#### Azure Windows VM

**Node View:**

- [ ] Info (Model After VM on Prem)
- [ ] Stats
- [ ] Storage
- [ ] CPU
- [ ] Memory
- [ ] Network

**Comment by stebet** [comment]
A small suggestion, maybe also add support for Azure Active Directory as an authentication provider? Or would consider that a separate issue/task since this is mostly about metrics?

**Comment by StefanKert** [comment]
Is there any news on this? Sounds like a good idea to me. Do you want to proceed within a fork or is this more a feature-request?

**Comment by AlexSikilinda** [comment]
To @stebet's point, I would also add authorization for Microsoft accounts, since a lot of people use Microsoft accounts to access Azure portal and Visual Studio Online.

**Comment by nickluu2018** [comment]
Does this branch is available
